### ISSUE TITLE
Generic Template default action is tightly coupled

### ISSUE THREAD

**Issue by SAP0312** [Clivern/Racter#9]
There is no option to remove the default action in the generic template.

**Comment by Clivern** [comment]
Hi @SAP0312,

Can you please explain which field is optional from here https://github.com/Clivern/Racter/blob/master/src/main/java/com/clivern/racter/senders/templates/GenericTemplate.java since based on facebook docs https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic it is required and when i build the payload, i check if not empty i add the element otherwise it won't added to the payload.

**Comment by SAP0312** [comment]
See the problem is if we don't want to add the default action object it gives null pointer exception as there's no null pointer check. And we can't pass all values as an empty string as "default_action_messenger_extensions" field is boolean type.

**Comment by Clivern** [comment]
Now I imagine the problem, I will work on a fix this week
please feel free to give it a try if that is urgent :)

**Comment by SAP0312** [comment]
Sure, I'll try to fix it.

**Comment by Clivern** [comment]
Nice, Thanks @SAP0312

**Comment by SAP0312** [comment]
I've raised a pull request but there seems to be some issue with Travis job.

**Comment by Clivern** [comment]
I will fix the build and then release a new version

**Comment by SAP0312** [comment]
Sure @Clivern.

**Comment by Clivern** [comment]
Version 1.0.5 released https://oss.sonatype.org/service/local/repositories/releases/content/com/clivern/racter/1.0.5/ it should take some time to reflect on maven central.

**Comment by Clivern** [comment]
@SAP0312 thanks for the fix! please feel free to open the ticket or create a new one if issue still exist.
